package com.androiddevs.mvvmnewsapp.ui

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName


/**
 *
 * entity mean that this class will be mirrored in sql database to be a table inside it , by using DAO ROOM interface
 *
 */
//adding entity annotation as to make it ok to be used by room database
//putting table name for this entity as to be used by room
//putting id as unique value to differentiate between articles by using the id and this id can be null
//putting annotation of primary key as to state that this is unique value for this table and will be auto generated adn will be incremented by system whenever
//a new value is created for ex first data class has id =1 and second data class has id =2 and this 1 and 2 is generated by system not us
@Entity(
    tableName = "articles"
)
data class Article(
    @PrimaryKey(autoGenerate = true)
    var id:Int?=null,
    val author: String,
    val content: String,
    val description: String,
    val publishedAt: String,
    val source: Source,
    val title: String,
    val url: String,
    val urlToImage: String
)